name: Terraform State Migration

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.5.0
  AWS_REGION: eu-north-1
  EKS_CLUSTER_NAME: retail-store
  TF_STATE_BUCKET: tfstate-509d3870-eu-north-1
  TF_STATE_KEY: eks/minimal/terraform.tfstate
  TF_STATE_LOCK_TABLE: retail-store-terraform-locks

jobs:
  migrate-state:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Migrate Local State to Remote Backend
      working-directory: terraform/eks/minimal
      run: |
        terraform init \
          -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ env.TF_STATE_KEY }}" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=${{ env.TF_STATE_LOCK_TABLE }}" \
          -migrate-state
